### ISSUE TITLE
Include version number in config page

### ISSUE THREAD

**Issue by clach04** [clach04/pebble_watchface_framework#10]
See https://github.com/mattrossman/forecaswatch2 to see how that was implemented:

  * https://github.com/mattrossman/forecaswatch2/blob/master/src/pkjs/clay/config.js#L1
  * https://github.com/mattrossman/forecaswatch2/blob/master/src/pkjs/clay/config.js#L273
  * https://github.com/mattrossman/forecaswatch2/commit/7cbca78820a8280df5ca17383d4772994ab5f74f

NOTE forecaswatch2 has a modified version of Clay so unclear what's required after including the meta data into config file

**Comment by clach04** [comment]
Not unexpectedly first test failed, GHA log extract:

    Waf: Leaving directory `/home/runner/work/pebble_watchface_framework/pebble_watchface_framework/build'
    Build failed
    Traceback (most recent call last):
      File "/home/runner/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Task.py", line 123, in process
        ret=self.run()
      File "/home/runner/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Task.py", line 47, in run
        return m1(self)
      File "/home/runner/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/extras/process_js.py", line 122, in run
        bld.fatal("JS bundling failed\n{}\n{}".format(e.stdout,e.stderr))
      File "/home/runner/.pebble-sdk/SDKs/current/sdk-core/pebble/.waf-1.7.11-951087d39789950ed009f0c86ce75e7b/waflib/Context.py", line 219, in fatal
        raise self.errors.ConfigurationError(msg,ex=ex)
    ConfigurationError: JS bundling failed
    Hash: 9612bdd109eda55b4855
    Version: webpack 1.15.0
    Time: 264ms
                   Asset    Size  Chunks             Chunk Names
        pebble-js-app.js  131 kB       0  [emitted]  main
    pebble-js-app.js.map  152 kB       0  [emitted]  main
       [0] multi main 40 bytes {0} [built]
       [1] /home/runner/.pebble-sdk/SDKs/4.3/sdk-core/pebble/common/include/_pkjs_shared_additions.js 528 bytes {0} [built]
       [2] ./src/pkjs/app.js 106 bytes {0} [built]
       [3] ./~/pebble-clay/dist/js/index.js 126 kB {0} [built]
       [4] /home/runner/.pebble-sdk/SDKs/4.3/sdk-core/pebble/common/include/_message_key_wrapper.js 179 bytes {0} [built]
       [5] ./build/js/message_keys.json 114 bytes {0} [built]
       [6] ./src/pkjs/config.js 1.6 kB {0} [built] [1 error]

    WARNING in ./~/pebble-clay/dist/js/index.js
    Critical dependencies:
    2:418-425 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
     @ ./~/pebble-clay/dist/js/index.js 2:418-425

    ERROR in ./src/pkjs/config.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../../../package.json in /home/runner/work/pebble_watchface_framework/pebble_watchface_framework/src/pkjs
     @ ./src/pkjs/config.js 1:11-43



    Build failed.
    yes: standard output: Broken pipe
    Error: Process completed with exit code 1.

**Comment by clach04** [comment]
Caused due to different path structure in this code base compared with forecaswatch2

**Comment by clach04** [comment]
Resolved in https://github.com/clach04/pebble_watchface_framework/commit/32301b44cba0a54b16b5a4329de909664c6be077
